FROM golang:1.24-alpine3.21

RUN apk update && apk add git

WORKDIR /app

COPY /backend /app

RUN go mod tidy && \
    go install github.com/air-verse/air@latest

EXPOSE 4000

CMD ["air", "-c", ".air.toml"]